from __future__ import annotations

from typing import List

__all__ = ["RingVerifier", "VRFOutput", "get_ring_commitment", "ietf_verify"]

class RingVerifier:
    def __init__(self, commitment: bytes, ring_size: int) -> None: ...
    def verify(self, data: bytes, ad: bytes, signature: bytes) -> None: ...

class VRFOutput:
    def __init__(self, output: bytes) -> None: ...
    def hash(self) -> bytes: ...

def get_ring_commitment(public_keys: List[bytes]) -> bytes: ...
def ietf_verify(public_key: bytes, data: bytes, ad: bytes, signature: bytes) -> None: ...
